Repository antvis/L7-boundary, pull requests merged in 2020-09, with the labels that each got.

#3 feat: 钻取地图drillUpEvent，drillDownEvent事件
  docs/demo/drilldown.jsx
  docs/demo/world.jsx
  docs/index.md
  package.json
  src/layer/baseLayer.ts
  src/layer/drillDown.ts
  src/layer/interface.ts
Labels: PR: unreviewed, enhancement

#4 chore: add travis
  .github/workflows/ci.yml
  package.json
Labels: PR: unreviewed, chore

#5 文档案例
  .umirc.ts
  docs/baselayer.en.md
  docs/baselayer.zh.md
  docs/demo/base.zh.md
  docs/demo/custom-drilldown.zh.md
  docs/demo/drilldown.zh.md
  docs/demo/examples/china.jsx
  docs/demo/examples/city.jsx
  docs/demo/examples/county.jsx
  docs/demo/examples/custom-drilldown.jsx
  docs/demo/examples/drilldown.jsx
  docs/demo/examples/fillcolor.jsx
  docs/demo/examples/province.jsx
  docs/demo/examples/update-data.jsx
  docs/demo/examples/world.jsx
  docs/demo/fillcolor.zh.md
  docs/demo/update-data.zh.md
  docs/index.md
  package.json
  src/config.ts
Labels: PR: unreviewed
